management:
  endpoints.web.exposure.include: health

springdoc:
  show-actuator: true

pokedex:
  external-apis:
    pokeapi.base-url: https://pokeapi.co/api/v2/pokemon-species
    funtranslations.url-pattern: https://funtranslations.com/api/{language}.json?text={text}
